language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  #- ruby-head # Currently dying with the following returned:
               # Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
  - jruby-head
  - 1.8.7
  - ree
bundler_args: --binstubs
